### ISSUE TITLE
builds on gnu compiler 6.3.0 fail

### ISSUE THREAD

**Issue by mwalzer** [OpenMS/OpenMS#2640]
using all contrib libs, OS alpine linux
```
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
```
fails at:
```
[ 10%] Building CXX object src/openms/CMakeFiles/OpenMS.dir/source/FORMAT/FASTAFile.cpp.o
[ 11%] Building CXX object src/openms/CMakeFiles/OpenMS.dir/source/FORMAT/FastaIterator.cpp.o
In file included from /usr/include/limits.h:8:0,
                 from /usr/include/fortify/wchar.h:20,
                 from /usr/include/c++/6.3.0/cwchar:44,
                 from /usr/include/c++/6.3.0/bits/postypes.h:40,
                 from /usr/include/c++/6.3.0/iosfwd:40,
                 from /opt/openms-src/src/openms/include/OpenMS/CONCEPT/Exception.h:41,
                 from /opt/openms-src/src/openms/include/OpenMS/FORMAT/FASTAFile.h:38,
                 from /opt/openms-src/src/openms/source/FORMAT/FASTAFile.cpp:35:
/opt/openms-contrib/include/seqan/file/file_page.h:76:22: error: expected '>' before numeric constant
     template <size_t PAGESIZE>
                      ^
/opt/openms-contrib/include/seqan/file/file_page.h:163:52: error: expected '>' before numeric constant
  template <typename TValue, typename TFile, size_t PAGESIZE>
                                                    ^
/opt/openms-contrib/include/seqan/file/file_page.h:184:52: error: expected '>' before numeric constant
  template <typename TValue, typename TFile, size_t PAGESIZE>
                                                    ^
/opt/openms-contrib/include/seqan/file/file_page.h:382:21: error: expected identifier before numeric constant
   enum            { PAGESIZE = PAGESIZE_ };
                     ^
/opt/openms-contrib/include/seqan/file/file_page.h:382:21: error: expected '}' before numeric constant
/opt/openms-contrib/include/seqan/file/file_page.h:382:21: error: expected unqualified-id before numeric constant
In file included from /opt/openms-contrib/include/seqan/file.h:113:0,
                 from /opt/openms-contrib/include/seqan/stream.h:70,
                 from /opt/openms-src/src/openms/source/FORMAT/FASTAFile.cpp:44:
/opt/openms-contrib/include/seqan/file/file_page.h:386:9: error: 'TIterator' does not name a type
         TIterator       begin;
         ^~~~~~~~~
/opt/openms-contrib/include/seqan/file/file_page.h:387:9: error: 'TIterator' does not name a type
         TIterator       end;
         ^~~~~~~~~
/opt/openms-contrib/include/seqan/file/file_page.h:388:9: error: invalid use of template-name 'seqan::AsyncRequest' without an argument list
         AsyncRequest    request;    // request structure of the async io process
         ^~~~~~~~~~~~
In file included from /opt/openms-contrib/include/seqan/file.h:70:0,
                 from /opt/openms-contrib/include/seqan/stream.h:70,
                 from /opt/openms-src/src/openms/source/FORMAT/FASTAFile.cpp:44:
/opt/openms-contrib/include/seqan/file/file_interface.h:154:12: note: 'template<class T> struct seqan::AsyncRequest' declared here
     struct AsyncRequest
            ^~~~~~~~~~~~
```

**Comment by mwalzer** [comment]
same for clang 4.0.0

**Comment by jpfeuffer** [comment]
Maybe they added a !define PAGESIZE to the stdlib headers.
Either undefine it (risky) or rename all occurrences in seqan.

**Comment by timosachsenberg** [comment]
by the way: thanks for testing on new compilers ;)

**Comment by timosachsenberg** [comment]
@mwalzer do you know if this error still occurs?

**Comment by mwalzer** [comment]
I can check next week

**Comment by hroest** [comment]
on the other hand we know that ubuntu sid with gcc 7.0 works, see this docker file: https://github.com/OpenMS/dockerfiles/pull/4/commits/1cd01573dbac84be4cd4d010555a2aa9a452c76a

now this is not with the contrib but with such a bleeding edge distro, you dont need the contrib any more and can get everything from package management.

Still it would be nice if contrib + OpenMS would compile and work on gcc 6/7

**Comment by jpfeuffer** [comment]
I can also let our nightlies download another (newer) compiler. Was planning that anyway. Or as @hroest said, we test them with the Docker containers.

**Comment by hroest** [comment]
@mwalzer is this still an issue?

**Comment by rmd06** [comment]
change all the PAGESIZE to PageSize

**Comment by cbielow** [comment]
seqan was removed in #5776, so closing
