### ISSUE TITLE
Compilation on g++ < 8 broken due to filesystem header

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#7051]
```
/workspace/OpenMS/src/openms/source/SYSTEM/File.cpp:52:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
```

Introduced in #7035 

https://cdash.openms.de/viewBuildError.php?buildid=148485

Please update min compiler version or ifdef the include to "experimental" in g++7

**Comment by jpfeuffer** [comment]
https://gitlab.kitware.com/cmake/cmake/-/issues/17834

Compiler-independent linking to the "extra" library std++fs is apparently not supported by CMake, so you have to write your own logic.

**Comment by jpfeuffer** [comment]
I commented out filesize measurement for now, such that it compiles. #7053 
Whoever tackles this issue, please remember to put it back.
