### PR TITLE
fix(openswath): resolve duplicate TLS init symbol on macOS clang

### LINKED ISSUE #9222: duplicate symbol 'thread-local initialization routine for OpenMS::g_picker_pool_shared'
@singjc: [this commit](https://github.com/OpenMS/OpenMS/commit/5da4322b7f875b12d25ee4871fc48b9f989d6a4e) seems to have broken the build on macOS arm64:

```
OpenMS> duplicate symbol 'thread-local initialization routine for OpenMS::g_picker_pool_shared' in:
OpenMS>     CMakeFiles/OpenMS.dir/source/ANALYSIS/OPENSWATH/MRMFeatureFinderScoring.cpp.o
OpenMS>     CMakeFiles/OpenMS.dir/source/ANALYSIS/OPENSWATH/OpenSwathWorkflow.cpp.o
OpenMS> ld: 1 duplicate symbol for architecture arm64
OpenMS> clang++: error: linker command failed with exit code 1 (use -v to see invocation)
OpenMS> make[2]: *** [src/openms/CMakeFiles/OpenMS.dir/build.make:11630: lib/libOpenMS.dylib] Error 1
OpenMS> make[1]: *** [CMakeFiles/Makefile2:3348: src/openms/CMakeFiles/OpenMS.dir/all] Error 2
OpenMS> make: *** [Makefile:146: all] Error 2
```

### PR DESCRIPTION
**Pull request by timosachsenberg**
## Summary
- Fixes #9222: `duplicate symbol 'thread-local initialization routine for OpenMS::g_picker_pool_shared'` on macOS arm64 introduced by #9190.
- Root cause: `PickerPoolShared g_picker_pool_shared` was declared `inline thread_local` at namespace scope in `MRMTransitionGroupPicker.h`. The type has a non-trivial constructor (vector members), so the compiler must emit a thread-local initialization wrapper. macOS Mach-O / clang does not always emit that wrapper as weak/COMDAT for `inline thread_local`, so every translation unit including the header (`MRMFeatureFinderScoring.cpp`, `OpenSwathWorkflow.cpp`, …) defined its own copy and the linker rejected the duplicates.
- Fix: standard pattern — `extern thread_local` declaration in the header, single definition in `MRMTransitionGroupPicker.cpp`. One TU emits the init wrapper, semantics unchanged (one instance per thread, lazy init on first access), no callsite changes.

## Test plan
- [x] Linux build clean: `cmake --build OpenMS-build --target OpenMS` → `[100%] Built target OpenMS`
- [ ] macOS arm64 CI link succeeds (was failing pre-fix)
- [ ] Existing OpenSwath tests still green

🤖 Generated with [Claude Code](https://claude.com/claude-code)

## Summary by CodeRabbit

* **Refactor**
  * Improved internal thread-safe resource management for enhanced library compatibility and stability.

### CODE REVIEW

File: src/openms/include/OpenMS/ANALYSIS/OPENSWATH/MRMTransitionGroupPicker.h [hunk 1]
```diff
@@ -71,8 +71,11 @@ namespace OpenMS
     }
   };
 
-  // Per-thread instances of the shared pools
-  inline thread_local PickerPoolShared g_picker_pool_shared;
+  // Per-thread instance of the shared pools.
+  // Defined in MRMTransitionGroupPicker.cpp: declaring it `inline thread_local`
+  // here triggers a duplicate "thread-local initialization routine" symbol on
+  // macOS clang because the TLS init wrapper is not always emitted as weak.
```
Comment (timosachsenberg) [inline src/openms/include/OpenMS/ANALYSIS/OPENSWATH/MRMTransitionGroupPicker.h]:
```suggestion
```

**Comment by timosachsenberg** [comment]
Pushed follow-up: `extern thread_local` alone wasn't enough on Linux because `-fvisibility=hidden` keeps the symbol out of libOpenMS's dynamic symbol table. The header has inline template member functions (`pickTransitionGroup`, `computeQuality_`) that reference `g_picker_pool_shared`, so consumers that instantiate them in another target (`src/topp/MRMTransitionGroupPicker.cpp`, `MRMTransitionGroupPicker_test.cpp`, …) emit an external relocation that the linker can't resolve. Added `OPENMS_DLLAPI` to declaration and definition; reproduced the `MRMTransitionGroupPicker_test` link failure locally and confirmed it links after the change. nm now shows `OpenMS::g_picker_pool_shared` and its TLS init function as global default-visibility entries in libOpenMS.so.

**Comment by timosachsenberg** [comment]
Pushed `b11b7fd4c8`: Windows MSVC was still failing with `LNK2019` linking the TOPP `MRMTransitionGroupPicker` tool — MSVC does not reliably support `__declspec(dllexport)` on a `thread_local` variable of a non-trivial type.

Replaced the namespace-scope `extern OPENMS_DLLAPI thread_local` with a function-local `thread_local static` returned by an inline accessor (Meyers'-singleton style). That avoids cross-DLL TLS export entirely and gives uniform behavior on macOS clang, Linux gcc/clang, and MSVC. Updated the six callsites in the header (most chained off a single `auto &pool = g_picker_pool_shared();`) and confirmed locally that `MRMTransitionGroupPicker_test` and all four `TOPP_MRMTransitionGroupPicker_test_*` tests still pass.
