### ISSUE TITLE
build error - failed type conversions

### ISSUE THREAD

**Issue by lopippo** [OpenMS/OpenMS#2894]
Greetings,

building OpenMS feature/qt5_working on Debian sid, I stumble upon this error:

In file included from /<<PKGBUILDDIR>>/src/openms/source/COMPARISON/CLUSTERING/GridBasedClustering.cpp:35:0:
/<<PKGBUILDDIR>>/src/openms/include/OpenMS/COMPARISON/CLUSTERING/GridBasedClustering.h: In member function 'void OpenMS::GridBasedClustering<Metric>::cluster()':
/<<PKGBUILDDIR>>/src/openms/include/OpenMS/COMPARISON/CLUSTERING/GridBasedClustering.h:186:52: error: no matching function for call to 'OpenMS::GridBasedClustering<Metric>::startProgress(int, OpenMS::Size&, const char [11])'
       startProgress(0, clusters_start, "clustering");
                                                    ^
In file included from /<<PKGBUILDDIR>>/src/openms/include/OpenMS/COMPARISON/CLUSTERING/GridBasedClustering.h:40:0,
                 from /<<PKGBUILDDIR>>/src/openms/source/COMPARISON/CLUSTERING/GridBasedClustering.cpp:35:
/<<PKGBUILDDIR>>/src/openms/include/OpenMS/CONCEPT/ProgressLogger.h:112:10: note: candidate: void OpenMS::ProgressLogger::startProgress(OpenMS::SignedSize, OpenMS::SignedSize, const OpenMS::String&) const
     void startProgress(SignedSize begin, SignedSize end, const String& label) const;
          ^~~~~~~~~~~~~
/<<PKGBUILDDIR>>/src/openms/include/OpenMS/CONCEPT/ProgressLogger.h:112:10: note:   no known conversion for argument 3 from 'const char [11]' to 'const OpenMS::String&'
src/openms/CMakeFiles/OpenMS.dir/build.make:12398: recipe for target 'src/openms/CMakeFiles/OpenMS.dir/source/COMPARISON/CLUSTERING/GridBasedClustering.cpp.o' failed

Thank you
Filippo Rusconi

**Comment by hroest** [comment]
Hi 

Thanks for reporting this, I think the branch you have is outdated. I suggest to use the feature/qt5 branch which has more fixes and I have just tested a few minutes ago. It compiles on my Ubuntu 16.04 laptop. See also this tracking feature: https://github.com/OpenMS/OpenMS/issues/2241
