### ISSUE TITLE
OpenMS does not compile with GCC 11.2.0

### ISSUE THREAD

**Issue by poshul** [OpenMS/OpenMS#6462]
This looks to be an error with GCC and sleep_for. See https://stackoverflow.com/questions/4438084/stdthis-threadsleep-for-and-gcc

**Comment by jpfeuffer** [comment]
What is the error?

**Comment by poshul** [comment]
`error: ‘sleep_for’ is not a member of ‘std::this_thread’`. It gets fixed by adding <thread> to include.
