### ISSUE TITLE
Error in FeatureFinderMetabo on Windows

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#2645]
Shadowed by general build failure due to C++11.
```
16>Build started 5/28/2017 10:34:59 PM.
15>FeatureFinderMetabo.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl OpenMS::FeatureFindingMetabo::run(class std::vector<class OpenMS::MassTrace,class std::allocator<class OpenMS::MassTrace> > &,class OpenMS::FeatureMap &,class std::vector<class std::vector<class OpenMS::MSChromatogram<class OpenMS::ChromatogramPeak>,class std::allocator<class OpenMS::MSChromatogram<class OpenMS::ChromatogramPeak> > >,class std::allocator<class std::vector<class OpenMS::MSChromatogram<class OpenMS::ChromatogramPeak>,class std::allocator<class OpenMS::MSChromatogram<class OpenMS::ChromatogramPeak> > > > > &)" (__imp_?run@FeatureFindingMetabo@OpenMS@@QEAAXAEAV?$vector@VMassTrace@OpenMS@@V?$allocator@VMassTrace@OpenMS@@@std@@@std@@AEAVFeatureMap@2@AEAV?$vector@V?$vector@V?$MSChromatogram@VChromatogramPeak@OpenMS@@@OpenMS@@V?$allocator@V?$MSChromatogram@VChromatogramPeak@OpenMS@@@OpenMS@@@std@@@std@@V?$allocator@V?$vector@V?$MSChromatogram@VChromatogramPeak@OpenMS@@@OpenMS@@V?$allocator@V?$MSChromatogram@VChromatogramPeak@OpenMS@@@OpenMS@@@std@@@std@@@2@@4@@Z) referenced in function "protected: virtual enum OpenMS::TOPPBase::ExitCodes __cdecl TOPPFeatureFinderMetabo::main_(int,char const * *)" (?main_@TOPPFeatureFinderMetabo@@MEAA?AW4ExitCodes@TOPPBase@OpenMS@@HPEAPEBD@Z)
15>C:\dev\KNIME_PACKAGE\trunk\OpenMS_build_x64\bin\Release\FeatureFinderMetabo.exe : fatal error LNK1120: 1 unresolved externals
15>
15>Build FAILED.
```

**Comment by jpfeuffer** [comment]
Probably introduced in #2615

**Comment by oliveralka** [comment]
I run osx, so it is hard for me to test, but I will have a look on it!

**Comment by hroest** [comment]
not sure about this, the `run` function was linking quite well before this PR?

**Comment by jpfeuffer** [comment]
Hmm.. maybe it was false alarm. I will leave it open until we have develop builds from Windows again.

**Comment by oliveralka** [comment]
@jpfeuffer let me know if issues occurs again - I looked at the code but have no explanation why it would not work - If it is necessary I could try to build it using a Win-VM.

**Comment by jpfeuffer** [comment]
Well there is definitely an error for the Python bindings:
```
pyopenms/pyopenms.cpp:661413:79: error: too few arguments to function call, expected 3, have 2
    __pyx_v_self->inst.get()->run((*__pyx_v_v0), (*__pyx_v_result->inst.get()));
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                             ^
/Users/builder/jenkins/ws/openms_nightly_supplement/a2d943f6/source/src/openms/include/OpenMS/FILTERING/DATAREDUCTION/FeatureFindingMetabo.h:176:5: note: 'run' declared here
    void run(std::vector<MassTrace>& input_mtraces, FeatureMap& output_featmap, std::vector<std::vector< OpenMS::MSChromatogram<> > >& output_chromatograms);
```
I am pretty sure there is also going something wrong on Windows.

**Comment by jpfeuffer** [comment]
But! Maybe the Windows error comes from an old library lying around. So wait for this one.

**Comment by jpfeuffer** [comment]
Seems fine now I think.
