### ISSUE TITLE
[Error] - Failed to compile with VS2019 MSVC 14.2

### ISSUE THREAD

**Issue by ahmedskhalil** [OpenMS/OpenMS#5020]
**Description**
OpenMS fails to compile with the aforementioned tools, the compiler complains about the missing header `algorithm` for the OpenSWATHAlgo, namely `Scoring.h`. The header was previously present as is required by `std::sort`.

The exact error is : `~\OpenMS\src\openswathalgo\source\OPENSWATHALGO\ALGO\Scoring.cpp(276,12): error C2039: 'sort': is not a member of 'std' [~\OpenMS\openms_build\src\openswathalgo\OpenSwathAlgo.vcxproj]`

**Comment by jpfeuffer** [comment]
Interesting. It compiles successfully in the nightly builds: http://cdash.openms.de/buildSummary.php?buildid=64211

Which exact version of 14.2 do you use?

Nonetheless, if you add the missing header and it still compiles on our testing machines, it should be fine.

**Comment by ahmedskhalil** [comment]
We're using MSVC `14.27.29110`. I had to automate adding the include directive to successfully build it in the CI.

**Comment by jpfeuffer** [comment]
ok, then you have a newer update than on our build machines. I will upgrade ours and check again. But most likely you are right, feel free to make a pull request if you need it right now.

**Comment by ahmedskhalil** [comment]
Thanks, I made a pull request #5022 to resolve this.

**Comment by jpfeuffer** [comment]
Thanks a lot!!
