### PR TITLE
[FIX] fix for compile error

### PR DESCRIPTION
**Pull request by hroest**
may fix the MSVS compile error

see the current compilation errors:

http://cdash.openms.de/viewBuildError.php?buildid=183885

```Error 	

3>/.../OpenMS/src/openms/source/FORMAT/IndexedMzMLFile.cpp(50): error C2666: 'std::fpos<_Statetype>::operator ==' : 3 overloads have similar conversions

3>          with
3>          [
3>              _Statetype=_Mbstatet
3>          ]
3>          c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\iosfwd(102): could be 'bool std::fpos<_Statetype>::operator ==(std::streamoff) const'
3>          with
3>          [
3>              _Statetype=_Mbstatet
3>          ]
3>          c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\iosfwd(97): or       'bool std::fpos<_Statetype>::operator ==(const std::fpos<_Statetype> &) const'


Repository 	https://github.com/OpenMS/OpenMS/blob/master/src/openms/source/ANALYSIS/ID/PeptideIndexing.cpp
Build Log Line 	111
Error 	

3>/.../OpenMS/src/openms/source/ANALYSIS/ID/PeptideIndexing.cpp(785): error C2784: 'void seqan::swap(seqan::StringSet<TString,TSpec> &,seqan::StringSet<TString,TSpec> &)' : could not deduce template argument for 'seqan::StringSet<TString,TSpec> &' from 'seqan::FoundProteinFunctor'

3>          C:\dev\contrib_vs10_64bit\include\seqan/sequence/string_set_base.h(291) : see declaration of 'seqan::swap'


Repository 	https://github.com/OpenMS/OpenMS/blob/master/src/openms/source/ANALYSIS/ID/PeptideIndexing.cpp
Build Log Line 	113
Error 	

3>/.../OpenMS/src/openms/source/ANALYSIS/ID/PeptideIndexing.cpp(785): error C2784: 'void seqan::swap(seqan::String<TValue,seqan::Alloc<TSpec>> &,seqan::String<TValue,seqan::Alloc<TSpec>> &)' : could not deduce template argument for 'seqan::String<TValue,seqan::Alloc<TSpec>> &' from 'seqan::FoundProteinFunctor'

3>          C:\dev\contrib_vs10_64bit\include\seqan/sequence/string_alloc.h(239) : see declaration of 'seqan::swap'


Repository 	https://github.com/OpenMS/OpenMS/blob/master/src/openms/source/ANALYSIS/ID/PeptideIndexing.cpp
Build Log Line 	115
Error 	

3>/.../OpenMS/src/openms/source/ANALYSIS/ID/PeptideIndexing.cpp(785): error C2784: 'void seqan::swap(seqan::String<TValue,TSpec> &,seqan::String<TValue,TSpec> &)' : could not deduce template argument for 'seqan::String<TValue,TSpec> &' from 'seqan::FoundProteinFunctor'

3>          C:\dev\contrib_vs10_64bit\include\seqan/sequence/string_base.h(185) : see declaration of 'seqan::swap'


Repository 	https://github.com/OpenMS/OpenMS/blob/master/src/openms/source/ANALYSIS/ID/PeptideIndexing.cpp
Build Log Line 	117
Error 	

3>/.../OpenMS/src/openms/source/ANALYSIS/ID/PeptideIndexing.cpp(785): error C3767: 'swap': candidate function(s) not accessible

3>          could be the friend function at 'C:\dev\NIGHTLY\OpenMS\src\openms\include\OpenMS/DATASTRUCTURES/ConstRefVector.h(583)' : 'swap'  [may be found via argument-dependent lookup]
3>          or the friend function at       'C:\dev\NIGHTLY\OpenMS\src\openms\include\OpenMS/DATASTRUCTURES/ConstRefVector.h(349)' : 'swap'  [may be found via argument-dependent lookup]
3>          or the friend function at       'C:\dev\NIGHTLY\OpenMS\src\openms\include\OpenMS/DATASTRUCTURES/ConstRefVector.h(583)' : 'swap'  [may be found via argument-dependent lookup]
3>          or the friend function at       'C:\dev\NIGHTLY\OpenMS\src\openms\include\OpenMS/DATASTRUCTURES/ConstRefVector.h(349)' : 'swap'  [may be found via argument-dependent lookup]


```

this may fix the first one, but the others still need fixing

@jpfeuffer  @cbielow can you comment on these errors ?

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Okay, I think the error was introduced in https://github.com/OpenMS/OpenMS/commit/9d1e30644269c4ab2bb23c93e5c4649bcaab2725
There is no swap method implemented for the FoundProteinFunctor. On linux the compilers might automatically choose std::swap after an unsuccessful lookup in the other namespaces but I am not sure.
@cbielow Did you have a particular swap function in mind when writing this? In other cases you also used seqan::move.

PS: I can easily test this PR for you manually. Automatic WinCI is ready soon.
I can also confirm that it removed the first error.

**Comment by hroest** [comment]
@jpfeuffer that would be great, maybe you can just use this branch and build on top of that so that we have all win fixes together ...

**Comment by hroest** [comment]
@jpfeuffer I could not reproduce these errors on MSVS 2010 but it seems that the cdash server has problems with MSVS 2010

Lets try and merge these two fixes and see what they do on cdash . It would be great to have MS Windows nightlies again!

**Comment by jpfeuffer** [comment]
+1 Yes I agree.

**Comment by hroest** [comment]
@jpfeuffer the good news is that it worked, the bad news is that there is no more space on the Windows disk:
```
155>C:\Users\OPENMS~1\AppData\Local\Temp\lnk495A.tmp : fatal error LNK1180: insufficient disk space to complete link
```

**Comment by jpfeuffer** [comment]
Yes, saw this. Already resolved. With a note to the admins to increase the size of the VM. This was due to recent CI testing on this machine.
