### ISSUE TITLE
pyOpenMS fails to compile on Ubuntu 14.04

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#1207]
pyOpenMS does not compile on Ubuntu 14.04 with vanilla configuration. Instead if fails with errors of the sort 

```
In file included from /usr/include/c++/4.8/array:35:0,
                 from /usr/include/boost/lexical_cast.hpp:155,
                 from /home/hroest/openms/source/OpenMS_trunk/src/openms/include/OpenMS/DATASTRUCTURES/ListUtils.h:48,
                 from /home/hroest/openms/source/OpenMS_trunk/src/openms/include/OpenMS/DATASTRUCTURES/DataValue.h:39,
                 from /home/hroest/openms/source/OpenMS_trunk/src/openms/include/OpenMS/DATASTRUCTURES/Param.h:39,
                 from /home/hroest/openms/source/OpenMS_trunk/src/openms/include/OpenMS/CONCEPT/UniqueIdGenerator.h:39,
                 from /home/hroest/openms/source/OpenMS_trunk/src/openms/include/OpenMS/CONCEPT/UniqueIdInterface.h:38,
                 from pyopenms/pyopenms.cpp:372:
/usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^

```

**Comment by hroest** [comment]
the main issue seems to be the `./autowrap/autowrap/data_files/boost` folder in the autowrap project, see https://github.com/uweschmitt/autowrap/tree/master/autowrap/data_files/boost which seems somehow incompatible with the system boost on Ubuntu 14.04 . If I move the folder, then the compilation proceeds further but at some point errors out due to memory limits. Maybe somebody could try on a 64 bit Ubuntu 14.04 system ?

**Comment by mwalzer** [comment]
I will give it a try tomorrow on mint17.

**Comment by hroest** [comment]
great, thanks. On a fresh install more or less the following should do it from the Python side

```
sudo apt-get install libpython-dev 
sudo apt-get install cython
sudo apt-get install python-nose 

cd ~/lib
git clone https://github.com/uweschmitt/autowrap.git
export PYTHONPATH=`pwd`/autowrap:$PYTHONPATH
rm -rf autowrap/autowrap/data_files/boost
# go to your OpenMS build dir
cmake -DCMAKE_PREFIX_PATH="/path/to/builds/contrib-build;/usr;/usr/local" -DPYOPENMS=On -DBOOST_USE_STATIC=OFF ..//OpenMS_trunk
make pyopenms
```

**Comment by mwalzer** [comment]
nope, cannot reproduce. 
Clean mint version:
copying build/lib.linux-x86_64-2.7/pyopenms/pyopenms.so -> pyopenms
[100%] Built target pyopenms
But I ran into the libqt4webkit problem albeit I had apt-get install  libqt4-webkit libqt4-opengl-dev(which wasnt installed with libqt4-dev either)

**Comment by mwalzer** [comment]
so in addition to the build instructions in doc I had to also install packages automake and pip.
And via pip the nose autowrap and cython.
Using the boost from the contrib worked fine with MAKE_PREFIX_PATH to contrib.
Will update doc later.

**Comment by hroest** [comment]
so did you did it with or without the `rm -rf autowrap/autowrap/data_files/boost` ?

**Comment by hroest** [comment]
PS: I now also have passing pyOpenMS tests on 14.04 so I think we are probably on a good track here. Apparently @mwalzer didnt even run into the autowrap boost issue 

PS: @mwalzer the problem is not the boost from the contrib but the extra boost stuff integrated into autowrap. I tried to use the system boost, mostly because I want this to work for the debian / Fedora packaging guys

**Comment by mwalzer** [comment]
okay, I just installed autowrap via packaging system. Should I include that into the documentation as well?

**Comment by timosachsenberg** [comment]
I used autwrap from git and ran ```rm -rf autowrap/autowrap/data_files/boost```
and it builds on Ubuntu 14.10

**Comment by hroest** [comment]
ok, I would use the git checkout since we dont know how up-to-date the packaged version is

**Comment by timosachsenberg** [comment]
what is the state? Is this still critical?

**Comment by grosenberger** [comment]
I can confirm this problem on OS X 10.9. The workaround for autorwap from @hroest solved the problem.

**Comment by hroest** [comment]
so it is more an autowrap problem than an OpenMS issue. As we have a workaround, I close the issue
